{
 "title": "Host",
 "description": "Docker host metrics",
 "tags": [ "system" ],
 "time": { "from": "now-15m", "to": "now" },
 "refresh": "10s",
 "templating": {
  "list": [
   {
    "name": "host",
    "label": "Host:",
    "query": {
     "query": "label_values(node_os_version, host)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "Uptime",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "node_time_seconds{host=\"$host\"} - node_boot_time_seconds{host=\"$host\"}"
    }
   ]
  },
  {
   "title": "CPU Idle",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 4, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "sum(rate(node_cpu_seconds_total{mode=\"idle\", host=\"$host\"}[1m])) * 100 / scalar(count(node_cpu_seconds_total{mode=\"user\", host=\"$host\"}))"
    }
   ]
  },
  {
   "title": "CPU Cores",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 8, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "machine_cpu_cores{host=\"$host\"}"
    }
   ]
  },
  {
   "title": "Available Memory",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "node_memory_MemAvailable_bytes{host=\"$host\"}"
    }
   ]
  },
  {
   "title": "Free Swap",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 16, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "node_memory_SwapFree_bytes{host=\"$host\"}"
    }
   ]
  },
  {
   "title": "Free Storage",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 20, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "sum(node_filesystem_free_bytes{host=\"$host\"})"
    }
   ]
  },
  {
   "title": "Load Average 1m",
   "type": "timeseries",
   "gridPos": { "h": 4, "w": 8, "x": 0, "y": 3 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "node_load1{host=\"$host\"}",
     "legendFormat": "load 1m"
    }
   ]
  },
  {
   "title": "Processes",
   "type": "timeseries",
   "gridPos": { "h": 4, "w": 8, "x": 8, "y": 3 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "node_procs_running{host=\"$host\"}",
     "legendFormat": "running"
    },
    {
     "expr": "node_procs_blocked{host=\"$host\"}",
     "legendFormat": "blocked by I/O"
    }
   ]
  },
  {
   "title": "Interrupts",
   "type": "timeseries",
   "gridPos": { "h": 4, "w": 8, "x": 16, "y": 3 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": " irate(node_intr_total{host=\"$host\"}[5m])",
     "legendFormat": "interrupts"
    }
   ]
  },
  {
   "title": "CPU Usage",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "sum(rate(node_cpu_seconds_total{host=\"$host\"}[1m])) by (mode) * 100 / scalar(count(node_cpu_seconds_total{mode=\"user\", host=\"$host\"}))",
     "legendFormat": "{{ mode }}"
    }
   ]
  },
  {
   "title": "Memory Usage",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 14 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "node_memory_MemTotal_bytes{host=\"$host\"} - (node_memory_MemFree_bytes{host=\"$host\"} + node_memory_Buffers_bytes{host=\"$host\"} + node_memory_Cached_bytes{host=\"$host\"})",
     "legendFormat": "Used"
    },
    {
     "expr": "node_memory_MemFree_bytes{host=\"$host\"}",
     "legendFormat": "Free"
    },
    {
     "expr": "node_memory_Buffers_bytes{host=\"$host\"}",
     "legendFormat": "Buffers"
    },
    {
     "expr": "node_memory_Cached_bytes{host=\"$host\"}",
     "legendFormat": "Cached"
    }
   ]
  },
  {
   "title": "I/O Usage",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 21 },
   "fieldConfig": { "defaults": { "unit": "Bps" } },
   "targets": [
    {
     "expr": "sum(irate(node_disk_read_bytes_total{host=\"$host\"}[1m]))",
     "legendFormat": "read"
    },
    {
     "expr": "sum(irate(node_disk_written_bytes_total{host=\"$host\"}[1m]))",
     "legendFormat": "written"
    },
    {
     "expr": "sum(irate(node_disk_io_time_seconds_total{host=\"$host\"}[1m]))",
     "legendFormat": "io time"
    }
   ]
  },
  {
   "title": "Network Usage",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 28 },
   "fieldConfig": { "defaults": { "unit": "Bps" } },
   "targets": [
    {
     "expr": "irate(node_network_receive_bytes_total{device!=\"lo\", host=\"$host\"}[1m])",
     "legendFormat": "In: {{ device }}"
    },
    {
     "expr": "irate(node_network_transmit_bytes_total{device!=\"lo\", host=\"$host\"}[1m])",
     "legendFormat": "Out: {{ device }}"
    }
   ]
  },
  {
   "title": "Swap Usage",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 35 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "node_memory_SwapTotal_bytes{host=\"$host\"} - node_memory_SwapFree_bytes{host=\"$host\"}",
     "legendFormat": "Used"
    },
    {
     "expr": "node_memory_SwapFree_bytes{host=\"$host\"}",
     "legendFormat": "Free"
    }
   ]
  },
  {
   "title": "Swap I/O",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 35 },
   "fieldConfig": { "defaults": { "unit": "Bps" } },
   "targets": [
    {
     "expr": "rate(node_vmstat_pswpin{host=\"$host\"}[1m]) * 4096 or irate(node_vmstat_pswpin{host=\"$host\"}[5m]) * 4096",
     "legendFormat": "In"
    },
    {
     "expr": "rate(node_vmstat_pswpout{host=\"$host\"}[1m]) * 4096 or irate(node_vmstat_pswpout{host=\"$host\"}[5m]) * 4096",
     "legendFormat": "Out"
    }
   ]
  }
 ]
}