---
apiVersion: 1

datasources:
  - name: Prometheus
    type: prometheus
    access: proxy
    orgId: 1
    url: http://prometheus:9090
    basicAuth: false
    isDefault: true
    editable: true

  # --- see https://grafana.com/docs/grafana/latest/datasources/loki/
  - name: Loki
    type: loki
    access: proxy
    url: http://loki:3100
    basicAuth: false
