---
name: Lint

on:
  push:
  
jobs:
  yamllint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - uses: actions/setup-python@v4
        with:
          python-version: '3.x'
          cache: 'pip'

      - name: Install test dependencies.
        run: pip3 install yamllint

      - name: Lint code.
        run: yamllint .
